### PR TITLE
IncrementalLoadingCollection documentation

### PR DESCRIPTION
**Pull request by marcominerva**

### CODE REVIEW

**Comment by jasonshortphd** [comment]
I will merge this in, but the /api/ directory is really only meant for auto generated docs and is wiped after each build.  These docs should come from source code comments if you want them.  In addition, we are going to remove the /api/ folder in early October because people are not using it.  Intellisense works better for api discovery, but if you have topics you want covered deeper we should look at where they belong in the main docs (not api).

**Comment by marcominerva** [comment]
On this pull request: https://github.com/Microsoft/UWPCommunityToolkit/pull/293, @deltakosh asked me to add some documentation about my contribution, so if you tell me the correct place to insert it, I will be happy to add my topics!

**Comment by deltakosh** [comment]
This is what you did here:) no need for more :D

**Comment by marcominerva** [comment]
Perfect, thank you again!

**Comment by deltakosh** [comment]
Sorry I was wrong :( We need a general documentation here:
https://github.com/Microsoft/UWPCommunityToolkit-docs/tree/master/en-us/helpers

**Comment by jasonshortphd** [comment]
That is correct - the /helpers directory is the right spot.

Also add a link to the specific page here:  https://github.com/Microsoft/UWPCommunityToolkit-docs/blob/master/en-us/codehelpers.md

That is the list of helpers referenced from the landing page.

**Comment by marcominerva** [comment]
OK, I will add the documentation as soon as possible!

**Comment by deltakosh** [comment]
Thanks!
And please have a look here to check if all is correct for you: https://justpaste.it/yrup

**Comment by marcominerva** [comment]
Yes, it's all correct :-) Thank you!

**Comment by deltakosh** [comment]
Ping.. we plan to ship this wed :)

**Comment by marcominerva** [comment]
I'll send the documentation within tomorrow, I promise ;-)

**Comment by deltakosh** [comment]
Thanks a lot!

**Comment by deltakosh** [comment]
Documentation is now hosted here:
https://github.com/Microsoft/UWPCommunityToolkit/tree/dev/docs

**Comment by marcominerva** [comment]
Perfect, so I'll add the documentation here: https://github.com/Microsoft/UWPCommunityToolkit/tree/dev/docs/helpers, right?

**Comment by deltakosh** [comment]
Correct :)

**Comment by jasonshortphd** [comment]
Correct.  Take a look at the other pages that are there for an idea (copy and use them as a starting point).  There is no longer a table of contents in the new structure.  Just drop the page in and it will be picked up automatically.

**Pull request merged**
